version = 1

[merge]
require_automerge_label = false
blacklist_title_regex = "^WIP.*"
blacklist_labels = ["work in progress", "on hold"]
method = "squash"
delete_branch_on_merge = true
block_on_reviews_requested = true
notify_on_conflict = true
optimistic_updates = true
prioritize_ready_to_merge = true
auto_approve_usernames = ["dependabot-preview"]